name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Version
        uses: beaconbrigade/package-json-version@v0.3
        id: get-version        
      - name: Install Packages
        run: npm ci
      - name: Build Extension
        run: npm run build
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Package
        run: vsce package
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get-version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: |
            Release of ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vscode-xschem-viewer-${{ steps.get-version.outputs.version }}.vsix
          asset_name: vscode-xschem-viewer-${{ steps.get-version.outputs.version }}.vsix
          asset_content_type: application/zip